version: '3.8'

services:
  web:
    build: ./
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    env_file:
      - ./.env.db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
  mongo_config:
