version: '3.8'

services:
  web:
    build: ./
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    env_file:
      - ./.env.db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    depends_on:
      - db
volumes:
  mongo_data:
  mongo_config:
